#! /usr/bin/env bash

__user_custom_prompt() {

    local last_command=$?

    local venv_color=${CLR[ylw]}
    local status_error=${CLR[bred]}
    local status_ok=${CLR[bgrn]}
    local nil=${CLR[reset]}

    local checkmark='\342\234\223'
    local fancy_x='\342\234\227'

    local venv=''
    if [[ ! -z $VIRTUAL_ENV ]]; then
        local venv="{${venv_color}${VIRTUAL_ENV##*/}${nil}}"
    fi

    # Don't treat CTRL+C (130) as an error. This may catch some
    # cases where we actually have an error, but these should be rare
    # enough, and this is just a simple prompt function after all
    if [[ $last_command == 0 ]] || [[ $last_command == 130 ]]; then
        local status="${status_ok}${checkmark}${nil}"
    else
        local status="${status_error}${fancy_x}${nil}"
    fi

    local before_git_data="${status} [\w]"
    local git_data="(%s)"
    local after_git_data="${venv}\n\$ "

    __git_ps1 "$before_git_data" "$after_git_data" "$git_data"
}

# PROMPT_DIRTRIM=3
PROMPT_COMMAND='__user_custom_prompt'
