#! /usr/bin/env bash

__user_custom_prompt() {

    local last_command=$?

    local yellow='\[\033[33m\]'
    local red='\[\033[01;31m\]'
    local green='\[\033[01;32m\]'
    local nil='\[\033[00m\]'

    local checkmark='\342\234\223'
    local fancy_x='\342\234\227'

    local venv=''
    if [[ ! -z $VIRTUAL_ENV ]]; then
        local venv="{${yellow}$(basename ${VIRTUAL_ENV})${nil}}"
    fi

    if [[ $last_command == 0 ]]; then
        local status="${green}${checkmark}${nil}"
    else
        local status="${red}${fancy_x}${nil}"
    fi

    local before_git_data="${status} [\w]"
    local git_data="(%s)"
    local after_git_data="${venv}\n\$ "

    __git_ps1 "$before_git_data" "$after_git_data" "$git_data"
}

# PROMPT_DIRTRIM=3
PROMPT_COMMAND='__user_custom_prompt'
