set nocompatible
set backspace=indent,eol,start
set history=700
set ruler
set showcmd
set incsearch
set nowrap
set mouse=a
set hlsearch
set encoding=utf8
set ffs=unix,dos,mac
set nobackup
set nowb
set noswapfile
set expandtab
set smarttab
set shiftwidth=4
set tabstop=4
set ignorecase
set smartcase
set number
set t_Co=256
set cursorline
set wildignore+=*.py[cod]
set splitbelow
set splitright
set virtualedit=block
set wildmenu
set wildmode=longest:full,full
set shortmess+=I
set cryptmethod=blowfish2
set laststatus=2

colorscheme peachpuff
inoremap jk <ESC>
nnoremap Q <nop>
let mapleader = ","
syntax on
filetype plugin on
filetype indent on
highlight CursorLine   cterm=NONE ctermfg=NONE ctermbg=236
highlight StatusLine   cterm=NONE ctermfg=NONE ctermbg=236
highlight StatusLineNC cterm=NONE ctermfg=NONE ctermbg=235

command! PythonCtags execute '!ctags -R --python-kinds=-i --languages=python .'
