set nocompatible
set nobackup
set nowritebackup
set noswapfile
set backspace=indent,eol,start
set encoding=utf8
set fileformats=unix,dos,mac
set history=700
set ruler
set showcmd
set incsearch
set nowrap
set mouse=a
set hlsearch
set expandtab
set smarttab
set shiftwidth=4
set tabstop=4
set ignorecase
set smartcase
set number
set t_Co=256
set cursorline
set wildignore+=*.py[cod]
set splitbelow
set splitright
set virtualedit=block
set wildmenu
set wildmode=longest:full,full
set shortmess+=I
set cryptmethod=blowfish
set laststatus=2

filetype plugin on
filetype indent on

syntax on
colorscheme peachpuff
highlight LineNr       cterm=NONE ctermfg=248  ctermbg=NONE
highlight CursorLine   cterm=NONE ctermfg=NONE ctermbg=236
highlight CursorLineNr cterm=NONE ctermfg=248  ctermbg=236
highlight StatusLine   cterm=NONE ctermfg=NONE ctermbg=236
highlight StatusLineNC cterm=NONE ctermfg=NONE ctermbg=235
highlight Search       cterm=NONE ctermfg=NONE ctermbg=237

let mapleader = ","
inoremap          jk    <ESC>
nnoremap <silent> <C-L> :<C-U>nohlsearch<bar>redraw<CR>
nnoremap          Q     @@

command! PythonCtags execute '!ctags -R --python-kinds=-i --languages=python .'
command! StripAnsi   execute '%s/\v[\?]\[.?([0-9]{1,2}(;[0-9]{1,2})?)?[lhmK]//g'
