#! /usr/bin/env bash

alias vi='vim'
alias ls='ls -l --group-directories-first --color=auto'
alias nosetests='nosetests --nocapture --nologcapture'
alias pgrep='pgrep -af'
alias pkill='pkill -f'
alias cosmo_idea='cd $HOME/work/cfy && workon cloudify && idea'
alias jekyll-serve='jekyll serve --limit_posts 1 -w'
alias grep='grep --color=auto'
alias c='workon cloudify'
alias userctl='systemctl --user'
alias manager='cfy ssh -c "sudo docker exec -it cfy bash"'
