#! /usr/bin/env bash

alias vi='vim'
alias ls='ls -l --group-directories-first --color=auto'
alias nosetests='nosetests --nocapture --nologcapture'
alias pgrep='pgrep -af'
alias pkill='pkill -f'
alias grep='grep --color=auto'
alias c='workon cloudify'
alias userctl='systemctl --user'
