#! /usr/bin/env bash

_pip_completion()
{
    COMPREPLY=( $( COMP_WORDS="${COMP_WORDS[*]}" \
                   COMP_CWORD=$COMP_CWORD \
                   PIP_AUTO_COMPLETE=1 $1 ) )
}
complete -o default -F _pip_completion pip

__user_cdconfiguration_completion()
{
    COMPREPLY=( $(compgen -W "$(\ls ~/work/cfy/configurations)" -- \
                "${COMP_WORDS[$COMP_CWORD]}" ) )
}
complete -F __user_cdconfiguration_completion cdconfiguration
