#! /usr/bin/env bash

__pip_completion()
{
    COMPREPLY=( $( COMP_WORDS="${COMP_WORDS[*]}" \
                   COMP_CWORD=$COMP_CWORD \
                   PIP_AUTO_COMPLETE=1 $1 ) )
}
complete -o default -F __pip_completion pip

__user_cdconfiguration_completion()
{
    COMPREPLY=( $(compgen -W "$(\ls ~/work/claw/configurations)" -- \
                "${COMP_WORDS[$COMP_CWORD]}" ) )
}
complete -F __user_cdconfiguration_completion cdconfiguration

__python_argcomplete() {
    local IFS=''
    COMPREPLY=( $(IFS="$IFS" \
                  COMP_LINE="$COMP_LINE" \
                  COMP_POINT="$COMP_POINT" \
                  _ARGCOMPLETE_COMP_WORDBREAKS="$COMP_WORDBREAKS" \
                  _ARGCOMPLETE=1 \
                  "$1" 8>&1 9>&2 1>/dev/null 2>/dev/null) )
    if [[ $? != 0 ]]; then
        unset COMPREPLY
    fi
}
complete -o nospace -o default -F __python_argcomplete clue
complete -o nospace -o default -F __python_argcomplete clee
