#! /usr/bin/env bash

__user_exports_pathadd() {
    if [ -d "$1" ] && [[ ":$PATH:" != *":$1:"* ]]; then
        export PATH="$1:$PATH"
    fi
}

__user_exports_pathadd "$HOME/opt/rabbitmq_server-3.5.6/sbin"
__user_exports_pathadd "$HOME/opt/riemann-0.2.6/bin"
__user_exports_pathadd "$HOME/bin"

export EDITOR=vim

export LC_COLLATE="C"

export HISTCONTROL=ignoredups

eval $(dircolors -b)
export LS_COLORS="$LS_COLORS:*.aiff=00;36:"
