#! /usr/bin/env bash

__user_setup_fasd() {
    local fasd_cache="$HOME/.cache/fasd/init"
    if [ ! -r $fasd_cache ]; then
        fasd --init posix-alias bash-hook bash-ccomp bash-ccomp-install > "$fasd_cache"
    fi
    source "$fasd_cache"
}

__user_setup_fasd
