#! /usr/bin/env bash

__user_setup_virtualenvwrapper() {
    local PYTHON_VERSION=$1
    # promt is created elsewhere
    export VIRTUAL_ENV_DISABLE_PROMPT=1
    export WORKON_HOME="$HOME/.virtualenvs/${PYTHON_VERSION}"
    export VIRTUALENVWRAPPER_PYTHON="$(which python${PYTHON_VERSION})"
    export VIRTUALENVWRAPPER_VIRTUALENV="$(which virtualenv${PYTHON_VERSION})"
    source virtualenvwrapper.sh
}

__user_setup_virtualenvwrapper 2
